import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";

const playfair = localFont({
  src: "../public/fonts/PlayfairDisplay-VariableFont_wght.ttf",
  weight: "600 700 800",
  variable: "--font-playfair",
  fallback: ["Playfair Display", "georgia", "New Times Roman", "serif"],
});

const Dm_Sans = localFont({
  src: "../public/fonts/DMSans-VariableFont_opsz,wght.ttf",
  weight: "300 400 500",
  variable: "--font-dm-sans",
  fallback: ["DM Sans", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} ${Dm_Sans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
